baseURL = "https://dkko.me/"
languageCode = "pt-br"
title = "dkko"

theme = "tale"

[Author]
    name = "Daniel Komesu"

[params]
    GoogleAnalytics4 = "G-RLSNHYP5C3"

[markup.goldmark.renderer]
    unsafe = true

[permalinks]
    posts = "/posts/:slug"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About Me"
    title = "About Me"
    url = "/about/"
    weight = 0
  [[menu.main]]
    identifier = "legal"
    name = "Legal"
    title = "Legal"
    url = "/legal/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0
