baseURL = "http://dkko.me/"
languageCode = "pt-br"
title = "dkko"

theme = "tale"

googleAnalytics = "UA-37695851-13"

[markup.goldmark.renderer]
    unsafe = true

[permalinks]
    posts = "/posts/:slug"
