baseURL = "https://dkko.me/"
languageCode = "pt-br"
title = "dkko"

theme = "tale"

googleAnalytics = "UA-37695851-13"

[Author]
    name = "Daniel Komesu"

[params]
    GoogleAnalytics4 = "G-RLSNHYP5C3"

[markup.goldmark.renderer]
    unsafe = true

[permalinks]
    posts = "/posts/:slug"
